name: Build docker images (scheduled)

on:
  push:
    branches:
      - ping_author
  repository_dispatch:
  workflow_call:
    inputs:
      image_postfix:
        required: true
        type: string
  schedule:
    - cron: "17 0 * * *"

concurrency:
  group: docker-images-builds
  cancel-in-progress: false

jobs:
  latest-docker:
    name: "Latest PyTorch + TensorFlow [dev]"
    runs-on:
      group: aws-general-8-plus
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Check out code
        uses: actions/checkout@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Update clone
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          python3 -m pip install docker-squash
          docker images
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/transformers-all-latest-gpu
          build-args: |
            REF=main
          outputs: |
            type=docker,name=my_image,compression=zstd,compression-level=22,force-compression=true

      - name: Update clone
        run: |
          ls -l ./
          ls -l ./docker
          docker images
          export PATH="/home/runner/.local/bin:$PATH"
          docker-squash -t my_image:squashed my_image:latest --load-image
          docker-squash -t my_image:squashed2 my_image:squashed --load-image
          docker-squash -t my_image:squashed3 my_image:squashed2 --load-image